name: publish

on: 
  push:
    paths:
      - 'Dockerfile'
      - 'git-*'
      - '*.sh'
      - '*.yaml'
      - '*.yml'
      - 'requirements.txt'

jobs:
  publish-tooling-base-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the hello-world Docker image
      run: |
        docker pull ghcr.io/lanixx-hh/tooling-base:latest || /bin/true
        docker build . --tag ghcr.io/lanixx-hh/tooling-base:latest
        docker run ghcr.io/lanixx-hh/tooling-base:latest
        docker push ghcr.io/lanixx-hh/tooling-base:latest
