name: publish

on: 
  push:
    paths:
      - 'Dockerfile'
      - 'git-*'
      - '*.sh'
      - '*.yaml'
      - '*.yml'
      - 'requirements.txt'

jobs:
  publish-tooling-base-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Install buildx
      uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true
    - name: Build tooling image for amd64
      run: |
        docker pull --platform linux/amd64  ghcr.io/lanixx-hh/tooling-base:latest || /bin/true
        docker build --platform linux/amd64 --tag ghcr.io/lanixx-hh/tooling-base:latest --cache-from ghcr.io/lanixx-hh/tooling-base:latest --push .
    - name: Build tooling image for linux/arm64/v8
      run: |
        docker pull --platform linux/arm64/v8 ghcr.io/lanixx-hh/tooling-base:latest || /bin/true
        docker build --platform linux/arm64/v8 --tag ghcr.io/lanixx-hh/tooling-base:latest --cache-from ghcr.io/lanixx-hh/tooling-base:latest --build-arg IMAGE=multiarch/alpine --build-arg TAG=arm64-edge --push .
